# Generated by Django 5.2.2 on 2025-08-27 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id_solicitacao', models.AutoField(primary_key=True, serialize=False)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('descricao_solicitacao', models.TextField(blank=True, null=True)),
                ('status_solicitacao', models.CharField(max_length=20)),
                ('observacoes_admin', models.TextField(blank=True, null=True)),
                ('data_ultima_atualizacao_status', models.DateTimeField(auto_now=True)),
                ('id_agendamento', models.ForeignKey(db_column='id_agendamento', on_delete=django.db.models.deletion.CASCADE, to='booking.agendamento')),
            ],
            options={
                'db_table': 'solicitacao',
            },
        ),
    ]
