# Generated by Django 5.2.2 on 2025-08-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id_recurso', models.AutoField(primary_key=True, serialize=False)),
                ('nome_recurso', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('capacidade', models.IntegerField(blank=True, null=True)),
                ('localizacao', models.CharField(blank=True, max_length=255, null=True)),
                ('status_recurso', models.CharField(max_length=20)),
                ('politicas_uso_especificas', models.TextField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'recurso',
            },
        ),
    ]
