# Generated by Django 5.2.2 on 2025-08-27 09:53

from django.db import migrations
from django.utils import timezone

def create_test_recursos(apps, schema_editor):
    Recurso = apps.get_model("resource", "Recurso")

    Recurso.objects.create(
        nome_recurso="Laboratório de Informática",
        descricao="Laboratório equipado com 25 computadores",
        capacidade=25,
        localizacao="Bloco A - Sala 101",
        status_recurso="disponivel",
        politicas_uso_especificas="Uso restrito a aulas de programação."
    )

    Recurso.objects.create(
        nome_recurso="Sala de Reuniões",
        descricao="Sala com projetor e mesa para 10 pessoas",
        capacidade=10,
        localizacao="Bloco B - Sala 202",
        status_recurso="disponivel",
        politicas_uso_especificas="Reservas limitadas a 2 horas."
    )

    Recurso.objects.create(
        nome_recurso="Auditório",
        descricao="Auditório principal da instituição",
        capacidade=100,
        localizacao="Bloco C - Térreo",
        status_recurso="disponivel",
        politicas_uso_especificas="Agendamentos precisam ser aprovados."
    )

def remove_test_recursos(apps, schema_editor):
    Recurso = apps.get_model("resource", "Recurso")
    Recurso.objects.filter(
        nome_recurso__in=["Laboratório de Informática", "Sala de Reuniões", "Auditório"]
    ).delete()

class Migration(migrations.Migration):

    dependencies = [
        ("resource", "0001_initial"),  # ajuste para a última migração existente
    ]

    operations = [
        migrations.RunPython(create_test_recursos, remove_test_recursos),
    ]
