# Generated by Django 5.2.2 on 2025-08-10 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='id_perfil',
            field=models.ForeignKey(db_column='id_perfil', null=True, on_delete=django.db.models.deletion.CASCADE, to='user_profile.perfilacesso'),
        ),
    ]
