# Generated by Django 5.2.2 on 2026-03-07 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id_agendamento', models.AutoField(primary_key=True, serialize=False)),
                ('data_inicio', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('data_fim', models.DateField()),
                ('hora_fim', models.TimeField()),
                ('status_agendamento', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('negado', 'Negado'), ('cancelado', 'Cancelado'), ('concluido', 'Concluído')], default='pendente', max_length=20)),
                ('data_ultima_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'agendamento',
            },
        ),
        migrations.CreateModel(
            name='AgendamentoPai',
            fields=[
                ('id_agendamento_pai', models.AutoField(primary_key=True, serialize=False)),
                ('finalidade', models.CharField(blank=True, max_length=255, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('software_necessario', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'agendamento_pai',
            },
        ),
        migrations.CreateModel(
            name='UsoImediato',
            fields=[
                ('id_uso', models.AutoField(primary_key=True, serialize=False)),
                ('finalidade', models.CharField(blank=True, max_length=255, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('duracao_minutos', models.PositiveIntegerField(default=120, help_text='Duração prevista em minutos')),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'uso_imediato',
                'ordering': ['-data_inicio'],
            },
        ),
    ]
