# Generated by Django 5.2.2 on 2025-09-22 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilAcesso',
            fields=[
                ('id_perfil', models.AutoField(primary_key=True, serialize=False)),
                ('nome_perfil', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('visibilidade', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'perfil_acesso',
            },
        ),
    ]
