# Generated by Django 5.2.2 on 2025-09-22 02:42

from django.db import migrations

def create_user_profiles(apps, schema_editor):
    """
    Cria os perfis de acesso iniciais do sistema, já com a visibilidade correta.
    """
    PerfilAcesso = apps.get_model('user_profile', 'PerfilAcesso')
    
    perfis = [
        {
            'nome_perfil': 'Administrador', 
            'descricao': 'Gerencia todo o sistema, recursos e agendamentos.',
            'visibilidade': False  # Administrador não é um perfil selecionável
        },
        {
            'nome_perfil': 'Servidor', 
            'descricao': 'Pode solicitar agendamentos de recursos.',
            'visibilidade': True
        },
        {
            'nome_perfil': 'Terceirizado', 
            'descricao': 'Pode registrar uso de laboratórios e visualizar a ocupação.',
            'visibilidade': True
        },
    ]

    for perfil_data in perfis:
        # Usa get_or_create para evitar duplicados se a migração for corrida novamente
        PerfilAcesso.objects.get_or_create(
            nome_perfil=perfil_data['nome_perfil'],
            defaults=perfil_data
        )

def remove_user_profiles(apps, schema_editor):
    """
    Remove os perfis de acesso criados.
    """
    PerfilAcesso = apps.get_model('user_profile', 'PerfilAcesso')
    PerfilAcesso.objects.filter(
        nome_perfil__in=['Administrador', 'Servidor', 'Terceirizado']
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_user_profiles, remove_user_profiles),
    ]