# Generated by Django 5.2.2 on 2025-08-27 15:54

from django.db import migrations

def create_user_profiles(apps, schema_editor):
    # Cria os perfis de acesso iniciais do sistema
    PerfilAcesso = apps.get_model('user_profile', 'PerfilAcesso')
    perfis = [
        {'nome_perfil': 'Administrador', 'descricao': 'Gerencia todo o sistema, recursos e agendamentos.'},
        {'nome_perfil': 'Servidor', 'descricao': 'Pode solicitar agendamentos de recursos.'},
        {'nome_perfil': 'Terceirizado', 'descricao': 'Pode registrar uso de laboratórios e visualizar a ocupação.'},
    ]

    for perfil_data in perfis:
        PerfilAcesso.objects.get_or_create(**perfil_data)

def remove_user_profiles(apps, schema_editor):
    # Remove os perfis de acesso criados
    PerfilAcesso = apps.get_model('user_profile', 'PerfilAcesso')
    PerfilAcesso.objects.filter(
        nome_perfil__in=['Administrador', 'Servidor', 'Terceirizado']
    ).delete()

class Migration(migrations.Migration):
    dependencies = [
        ('user_profile', '0001_initial'),
    ]
    operations = [
        migrations.RunPython(create_user_profiles, remove_user_profiles),
    ]