# Generated by Django 5.2.2 on 2025-09-10 22:44

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_seed_user_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilacesso',
            name='visibilidade',
            field=models.BooleanField(default=True),
        ),
    ]
